[package]
name = "rust-blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"

# Serialization and desere... JSON
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"

# Timestamps
chrono = { version = "0.4", features = ["serde"]}

uuid = { version = "1.0", features = ["v4"]}

log = "0.4"
env_logger = "0.11"

hex = "0.4"
actix-web = "4"
# partage de blockchain entre plusieurs threads de maniere secu
tokio = {version = "1", features= ["full"]}

